"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "./lib";
import { AppHeader, ErrorNotice, Panel } from "./components";

type Project = { id: string; name: string; description?: string; environments: Array<{ type: string; baseUrl: string }>; _count: { trafficRequests: number; replayRuns: number } };
export default function ProjectsPage() {
  const client = useQueryClient(); const [showForm, setShowForm] = useState(false); const [error, setError] = useState<string | null>(null);
  const projects = useQuery<{ data: Project[] }>({ queryKey: ["projects"], queryFn: () => api("/api/v1/projects") });
  const create = useMutation({ mutationFn: (body: unknown) => api<{ data: Project }>("/api/v1/projects", { method: "POST", body: JSON.stringify(body) }), onSuccess: (response) => { client.invalidateQueries({ queryKey: ["projects"] }); location.href = `/projects/${response.data.id}`; }, onError: (cause) => setError(cause instanceof Error ? cause.message : "Unable to create project.") });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ name: form.get("name"), description: form.get("description") || undefined, environments: [{ type: "BASELINE", baseUrl: form.get("baseline"), timeoutMs: 5000, enabled: true }, { type: "CANDIDATE", baseUrl: form.get("candidate"), timeoutMs: 5000, enabled: true }] }); };
  return <main className="shell"><AppHeader /><div className="mb-6 flex items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-blue-700">PROJECTS</p><h1 className="m-0 text-3xl font-semibold tracking-tight">API regression workspaces</h1><p className="mb-0 mt-2 text-slate-600">Import representative traffic and compare a candidate API against its baseline.</p></div><button className="btn" onClick={() => setShowForm((value) => !value)}>New project</button></div>{error && <div className="mb-4"><ErrorNotice error={new Error(error)} /></div>}{showForm && <Panel title="New project"><form className="grid gap-4 p-5 md:grid-cols-2" onSubmit={submit}><label className="text-sm font-medium">Name<input required name="name" className="input mt-1" placeholder="Checkout API" /></label><label className="text-sm font-medium">Description<input name="description" className="input mt-1" placeholder="Regression checks before deployment" /></label><label className="text-sm font-medium">Baseline URL<input required type="url" name="baseline" className="input mt-1" placeholder="http://localhost:3001" /></label><label className="text-sm font-medium">Candidate URL<input required type="url" name="candidate" className="input mt-1" placeholder="http://localhost:3002" /></label><div className="md:col-span-2"><button className="btn" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create project"}</button></div></form></Panel>}<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.isError && <ErrorNotice error={projects.error} />}{projects.data?.data.map((project) => <Link key={project.id} href={`/projects/${project.id}`} className="card p-5 transition hover:border-blue-300"><div className="flex items-start justify-between gap-3"><h2 className="m-0 text-lg font-semibold">{project.name}</h2><span className="code text-xs text-slate-500">{project._count.trafficRequests} requests</span></div><p className="min-h-10 text-sm text-slate-600">{project.description || "No description"}</p><div className="space-y-1 text-sm text-slate-600">{project.environments.map((environment) => <p key={environment.type} className="m-0"><span className="mr-2 inline-block w-20 text-xs font-bold text-slate-400">{environment.type}</span><span className="code">{environment.baseUrl}</span></p>)}</div></Link>)}{projects.data?.data.length === 0 && <div className="card col-span-full p-8 text-center text-slate-600">No projects yet. Create one or run the included demo seed.</div>}</div></main>;
}
