"use client";
import { FormEvent, useState } from "react";
import { useParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../../../lib";
import { AppHeader, ErrorNotice, Panel } from "../../../components";

export default function ConfigurationPage() {
  const { id } = useParams<{ id: string }>(); const client = useQueryClient(); const [error, setError] = useState<string | null>(null);
  const project = useQuery<any>({ queryKey: ["project", id], queryFn: () => api(`/api/v1/projects/${id}`) });
  const rules = useQuery<any>({ queryKey: ["rules", id], queryFn: async () => ({ redaction: await api(`/api/v1/projects/${id}/redaction-rules`), ignore: await api(`/api/v1/projects/${id}/ignore-rules`) }) });
  const credentials = useQuery<any>({ queryKey: ["credentials", id], queryFn: async () => ({ BASELINE: await api(`/api/v1/projects/${id}/environments/BASELINE/credentials`), CANDIDATE: await api(`/api/v1/projects/${id}/environments/CANDIDATE/credentials`) }) });
  const update = useMutation({ mutationFn: (body: any) => api(`/api/v1/projects/${id}`, { method: "PATCH", body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ["project", id] }), onError: (cause) => setError(cause instanceof Error ? cause.message : "Unable to save configuration.") });
  const addRedaction = useMutation({ mutationFn: (body: any) => api(`/api/v1/projects/${id}/redaction-rules`, { method: "POST", body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ["rules", id] }) });
  const addIgnore = useMutation({ mutationFn: (body: any) => api(`/api/v1/projects/${id}/ignore-rules`, { method: "POST", body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ["rules", id] }) });
  const addCredential = useMutation({ mutationFn: ({ type, ...body }: any) => api(`/api/v1/projects/${id}/environments/${type}/credentials`, { method: "POST", body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ["credentials", id] }) });
  if (project.isLoading) return <main className="shell"><AppHeader projectId={id} /><p>Loading configuration…</p></main>; if (project.isError) return <main className="shell"><AppHeader projectId={id} /><ErrorNotice error={project.error} /></main>;
  const item = project.data.data; const policy = item.regressionPolicy;
  const byType = Object.fromEntries(item.environments.map((environment: any) => [environment.type, environment]));
  return <main className="shell">
    <AppHeader projectId={id} />
    <div className="mb-6"><p className="mb-1 text-sm font-medium text-blue-700">CONFIGURATION</p><h1 className="m-0 text-3xl font-semibold tracking-tight">Replay safety and comparison policy</h1></div>
    {error && <div className="mb-4"><ErrorNotice error={new Error(error)} /></div>}
    <div className="grid gap-5 lg:grid-cols-2">
      <Panel title="Environments"><form className="grid gap-4 p-5" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); update.mutate({ environments: ["BASELINE", "CANDIDATE"].map((type) => ({ type, baseUrl: form.get(`${type}-url`), timeoutMs: Number(form.get(`${type}-timeout`)), enabled: form.get(`${type}-enabled`) === "on", headers: byType[type].headers ?? {} })) }); }}>
        {(["BASELINE", "CANDIDATE"] as const).map((type) => <fieldset className="grid gap-2 rounded border border-slate-200 p-3" key={type}><legend className="px-1 text-xs font-bold text-slate-500">{type}</legend><label className="text-sm">Base URL<input className="input mt-1" name={`${type}-url`} type="url" defaultValue={byType[type].baseUrl} required /></label><label className="text-sm">Timeout (ms)<input className="input mt-1" name={`${type}-timeout`} type="number" min="100" defaultValue={byType[type].timeoutMs} required /></label><label className="text-sm"><input className="mr-2" name={`${type}-enabled`} type="checkbox" defaultChecked={byType[type].enabled} />Enabled</label></fieldset>)}
        <button className="btn w-fit" disabled={update.isPending}>Save environments</button>
      </form></Panel>
      <Panel title="Replay settings"><form className="grid gap-4 p-5" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); update.mutate({ maxConcurrency: Number(form.get("concurrency")), requestsPerSecond: form.get("rps") ? Number(form.get("rps")) : null, allowWriteMethods: form.get("writes") === "on" }); }}><label className="text-sm font-medium">Maximum concurrency<input className="input mt-1" name="concurrency" type="number" min="1" max="25" defaultValue={item.maxConcurrency} /></label><label className="text-sm font-medium">Requests per second (optional)<input className="input mt-1" name="rps" type="number" min="1" defaultValue={item.requestsPerSecond || ""} /></label><label className="flex gap-2 text-sm"><input type="checkbox" name="writes" defaultChecked={item.allowWriteMethods} />Allow POST, PUT, PATCH, and DELETE replay</label><p className="m-0 text-xs text-amber-700">Write methods may cause side effects. Enable them only with safe test targets and sanitized payloads.</p><button className="btn w-fit" disabled={update.isPending}>Save replay settings</button></form></Panel>
      <Panel title="Regression policy"><form className="grid gap-4 p-5" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); update.mutate({ policy: { failOnStatusChange: true, failOnRemovedFields: true, failOnTypeChange: true, latencyWarningPercent: Number(form.get("warning")), latencyFailurePercent: Number(form.get("failure")), latencyMinimumMs: Number(form.get("minimum")), selectedResponseHeaders: [] } }); }}><label className="text-sm font-medium">Latency warning percent<input className="input mt-1" name="warning" type="number" min="0" defaultValue={policy.latencyWarningPercent} /></label><label className="text-sm font-medium">Latency failure percent<input className="input mt-1" name="failure" type="number" min="0" defaultValue={policy.latencyFailurePercent} /></label><label className="text-sm font-medium">Baseline latency minimum (ms)<input className="input mt-1" name="minimum" type="number" min="0" defaultValue={policy.latencyMinimumMs} /></label><button className="btn w-fit" disabled={update.isPending}>Save policy</button></form></Panel>
      <Panel title="Credentials"><div className="space-y-5 p-5">{(["BASELINE", "CANDIDATE"] as const).map((type) => <section key={type}><p className="mb-2 text-xs font-bold text-slate-500">{type}</p><form className="mb-2 flex gap-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); addCredential.mutate({ type, headerName: form.get("headerName"), value: form.get("value") }); event.currentTarget.reset(); }}><input className="input" name="headerName" required placeholder="Authorization" /><input className="input" name="value" required type="password" placeholder="Secret value" /><button className="btn">Save</button></form><p className="m-0 text-xs text-slate-500">Stored encrypted; only header names are shown: {credentials.data?.[type].data.map((credential: any) => credential.headerName).join(", ") || "none"}</p></section>)}</div></Panel>
      <Panel title="Redaction rules"><div className="p-5"><form className="mb-4 flex gap-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const value = String(form.get("rule")); addRedaction.mutate(value.startsWith("$") ? { jsonPath: value, action: form.get("action") } : { headerName: value, action: form.get("action") }); event.currentTarget.reset(); }}><input className="input" name="rule" required placeholder="Authorization or $.payment.cardNumber" /><select className="input w-28" name="action"><option>REDACT</option><option>REMOVE</option></select><button className="btn">Add</button></form><ul className="m-0 space-y-2 p-0 text-sm">{rules.data?.redaction.data.map((rule: any) => <li className="list-none rounded bg-slate-50 p-2 code" key={rule.id}>{rule.headerName || rule.jsonPath} · {rule.action}</li>)}</ul></div></Panel>
      <Panel title="Ignored response fields"><div className="p-5"><form className="mb-4 flex gap-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); addIgnore.mutate({ jsonPath: form.get("path"), endpointPattern: form.get("endpoint") || undefined }); event.currentTarget.reset(); }}><input className="input" name="path" required placeholder="$.requestId" /><input className="input" name="endpoint" placeholder="GET /orders/*" /><button className="btn">Add</button></form><ul className="m-0 space-y-2 p-0 text-sm">{rules.data?.ignore.data.map((rule: any) => <li className="list-none rounded bg-slate-50 p-2 code" key={rule.id}>{rule.jsonPath}{rule.endpointPattern ? ` · ${rule.endpointPattern}` : ""}</li>)}</ul></div></Panel>
    </div>
  </main>;
}
